### PR TITLE
Adds ssss; upgrades electrum

### PR DESCRIPTION
**Pull request by bogomip2k**
Upgrades electrum to 2.9.0; adds support for Shamir's secret splitting scheme

### CODE REVIEW

**Comment by bogomip2k** [comment]
I was kinda confused by the need to recreate electrum from source rather than just use the debian package installer instead.  I've used the installer and it appears to work fine.  Am I missing something?

**Comment by Linearfire** [comment]
Okay, so I am a noob; How the heck can I build your upgrade into the ISO? OR heck even build it in general? Do I need a VM machine?

**Comment by bogomip2k** [comment]
The pull request should be approved and then it will be automatically incorporated into the next release.

On Nov 10, 2017, at 2:13 PM, Linearfire <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, so I am a noob; How the heck can I build your upgrade into the ISO? OR heck even build it in general? Do I need a VM machine?

**Comment by JedMeister** [comment]
Apologies on slow turnaround on your PR. I'm not closely involved in BitKey and don't have much to do with bitcoin. As it's essentially a side project, its not a big priority for me. Having said that, thanks tons for your contribution.

Whilst pip is a much easier way to install packages, pip security is fundamentally broken. That is why we aren't using it and instead are including the code archives, along with hashes (to make it easy for users to confirm that they match what is available via pip). We also do a code review of the python code that is included to ensure that there isn't anything malicious being accidentally included.

I really hope that pip eventually get around to solving their security deficiencies, so then we can start leverage the ease of use that pip provides.

**Comment by JedMeister** [comment]
Hey @bogomip2k, thanks for submitting your pull request. I'm really sorry that nothing happened with it. :cry: 

I'm going to close it now, not because there is anything wrong with it, but because we're doing a really crap job of maintaining this project and have now installed a new community lead developer. Have a read here: #56

I suggest that you rebase your original PR on the new community branch and issue a new pull request (against the community branch rather than master). Hopefully @estevaocm will do a much better job of it all than we've been doing...

**Pull request closed without merging**
