### PR TITLE
Add armory to bitkey

### PR DESCRIPTION
**Pull request by aghamir**
Hi,
I've added armory to bitkey. Can you check it?
Thanks

### CODE REVIEW

**Comment by estevaocm** [comment]
Hello @aghamir , thank you for contributing.

I must ask where is this version from. I haven't found it at https://github.com/goatpig/BitcoinArmory/releases or https://www.bitcoinarmory.com/download/

**Comment by estevaocm** [comment]
All binaries in Bitkey must be verifiable for security. Of course, I understand that none of us can be responsible if a particular binary is taken down by the developers, but this is recent. Optionally, you might update the pull request with a newer version. Thank you.

**Comment by quantumproducer** [comment]
@estevaocm  thank you for protecting the integrity of Bitkey.

**Comment by aghamir** [comment]
The binary is here:
https://github.com/goatpig/BitcoinArmory/releases/download/v0.96.3.992/armory_0.96.3.992-gcc4.7_amd64.deb
It is named 0.96.4 RC3.
It is necessary to check all binaries for bitkey integrity and if this is not the acceptable binary I will be happy you se

**Comment by aghamir** [comment]
Sorry I don't have access to my laptop and in mobile I cannot edit previous comment.
It my appreciate you send the truthfully binary link for armory if link above not acceptable one. I will fix it ASAP when I accessed to my laptop

**Comment by estevaocm** [comment]
@aghamir, thank you for the clarification. I was also able to verify the signature file at https://github.com/goatpig/BitcoinArmory/releases/download/v0.96.3.992/sha256sum.txt.asc so the deb is verifiable and the pull request may be accepted.

Actually, I was mistaken, I only read the title 0.96.4 RC3 and failed to notice the actual file is named armory_0.96.3.992-gcc4.7_amd64.deb, which is exactly the one you submitted.

**Pull request merged**
