### PR TITLE
Webcam support + wallets for altcoins

### PR DESCRIPTION
**Pull request by estevaocm**
Added:
* Webcam support (cheese) for QR code scanning so no USB communication is necessary
* Electrum-LTC
* Electron CASH
* MyEtherWallet
* Minimalist Ripple Client
* Monero wallet generator
* IOTA seed generator
* IOTA paper wallet
* BIP39 wallet (23 cryptocurrencies supported)
* Exodus wallet (many cryptocurrencies and ShapeShift supported)

Upgrades:
* Electrum 3.0.3
* Chromium 63
* Coinb.in 2017-12-09

### CODE REVIEW

**Comment by gerardbosch** [comment]
Great job @estevaocm ! I was really looking for an offline solution that integrates multiple cryptocurrencies as a kind of multi currency wallet. Just to clarify myself, 2 questions:

Are all the avobe listed cryptocurrencies from your fork ready to sign transactions offline?
And are the ALT wallets (and its keys) stored in the same encrypted USB stick the same way Bitkey does with Electrum for Bitcoin?

I wish this could become a universal wallet solution for cold storage/signing.

Thanks for your great contribution!!

**Comment by estevaocm** [comment]
Hi @gerardbosch , thank you for your support.

Right now, only Electrum, Electrum-LTC, Electrum-Dash and Electron-Cash are saving to the USB stick. Other wallets must be saved manually.

Only those four and MyEtherWallet currently can sign transactions offline. The others can only sign online, so I'd treat them as passive paper wallets until the time comes to withdraw all funds.

It seems quite impossible to become a universal cold wallet solution because there are over a thousand cryptocurrencies and new ones are being created almost every week. So I'm trying to focus on the top 10 market caps or so, or the most estabilished ones.

BTW, check out my fork repository, there's a new release from yesterday. Cheers!

**Comment by gerardbosch** [comment]
Thx for your answer @estevaocm  
I see you dropped the 2nd boot option (cold-online). What is the purpose for it?
And another question, you included Exodus but I think this is not Open Source. Could it be dangerous to rely on non-OSS to deal with our money? or I am wrong? Thanks :)

**Comment by estevaocm** [comment]
Cold-online mode relied on the "deseed" function of Electrum, which was dropped in version 3. Its function was to operate only public key operations, i.e., everything except signing. This can be accomplished just as well on Android or any online PC (including Bitkey in hot-online mode) by importing the master public key.

Exodus is supposedly mostly open source. I experimented with it a bit but moved on. It was useful for exchanging currencies, but nowadays I send Bitcoin Cash to a foreign exchange to the same effect, or operate ShapeShift manually. I kept it in Bitkey as an option, but users should be responsible for their own decisions. As Liraz says, if you wonder if you can trust Bitkey, don't. (Compile yourself, don't trust anything proprietary etc.)

**Comment by JedMeister** [comment]
Wow @estevaocm! You have been super busy! That's nuts! Great work.

Apologies that I've not been around more recently.

I'm flying to Sydney tomorrow morning and will be there for 10 days (flying back Mon 29th). Once I get back, I'd love to have a quick chat with you @estevaocm.

**Comment by estevaocm** [comment]
Hey @JedMeister . A security vulnerability in Electrum was exposed so I went to work patching up Bitkey! Also included some new tools I've been toying with.

No need for apologies, I've been pretty busy myself. We'll talk when you get back.

**Comment by aghamir** [comment]
What's is the status of this PR. I'm so excited to use this PR

**Comment by estevaocm** [comment]
Hello @aghamir, you may use the release published at my fork's page.

**Comment by mobilechan** [comment]
Would it be safe/secure to use a backwards-compatible SegWit address, P2SH-wrapped-P2WPKH, (starts with a 3) following this procedure for the BitKey Electrum wallet? 

https://www.reddit.com/r/Bitcoin/comments/7mpz5w/psa_contrary_to_popular_belief_electrum_does/

Thank you.

**Comment by estevaocm** [comment]
@mobilechan, I'd personally bet my funds on it. In fact my Bitkey fork includes the BIP39 wallet referred to in the link.

**Comment by mobilechan** [comment]
That's what I thought, but when I selected create SegWit wallet, bc1 addresses were generated. I will go back and see where I went wrong.  Hands down, your fork is my favorite. Thank you.

**Comment by mobilechan** [comment]
I was able to get the Segwit P2SH type (starts with 3) operational in the Electrum wallet, but noticed a Revealer plugin that has me concerned as I cannot find any information on it:

This plug-in allows you to create a Analog multi-factor backup of your wallet seeds.
For more information, visit  https://revealer(dot)info

**Review by matiaslb — COMMENTED** [review]
Commit [e1deab9](https://github.com/bitkey/bitkey/pull/54/commits/e1deab90be5e26266f4f42cb39b6ed2681c277ae) shouldn't be merged into bitkey:master

**Comment by JedMeister** [comment]
I'm going to close this PR now, seeing as your master branch is now merged into the community branch, which is now the default branch.

**Comment by JedMeister** [comment]
@matiaslb - FWIW, I branched a new community branch (from master) and have merged all @estevaocm changes (from his master branch). After doing that, I adjusted that and added a paragraph explaining the new community branch (see https://github.com/bitkey/bitkey/commit/fbf10a87d156ab9c353e9bc1be709aea19aee3a7). I also added the `--depth 1` switch so users only do a shallow clone (saves tons of time!).

**Pull request closed without merging**
